apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/Shaked/playground
          revision: main
          files:
            - path: charts/apps/**/values.yaml
      - clusters: {}
  template:
    metadata:
      name: 'apps-{{ index .path.segments 2 }}-{{ index .path.segments 3 }}'
    spec:
      project: "apps"
      source:
        repoURL: https://github.com/Shaked/playground
        targetRevision: main
        path: "charts/apps/{{ index .path.segments 2 }}/{{ index .path.segments 3 }}"
      destination:
        server: "{{ .server }}"
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
