apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/Shaked/playground
          revision: main
          files:
            - path: charts/apps/**/values.yaml
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
              argocd.argoproj.io/product-{{ index .path.segments 2 }}: "true"
          values:
            region: '{{ index .metadata.labels "region" }}'
            clusterName: '{{ .name }}'
  template:
    metadata:
      name: '{{ .name }}-apps-{{ index .path.segments 2 }}-{{ index .path.segments 3 }}'
    spec:
      project: "apps"
      source:
        repoURL: https://github.com/Shaked/playground
        targetRevision: main
        path: "charts/apps/{{ index .path.segments 2 }}/{{ index .path.segments 3 }}"
        helm:
          releaseName: '{{ dig "releaseName" (printf "%s-%s" (index .path.segments 2) (index .path.segments 3)) . }}'
          ignoreMissingValueFiles: true
          parameters:
          - name: region
            value: '{{ .values.region }}'
          valueFiles:
          - '../../../values/common-{{ index .path.segments 2 }}.yaml'
          - '../../../values/{{ index .path.segments 2 }}/{{.name}}/values.yaml'
      destination:
        server: "{{ .server }}"
        namespace: "{{ index .path.segments 2 }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
