## A working app1 of apps
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloud-specific-infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/Shaked/playground
          revision: main
          files:
            - path: charts/infra/*/argo.yaml
          values:
            environment: '{{ index .path.segments 2 }}'
      - clusters:
          selector:
            matchExpressions:
            - key: cloudProvider
              operator: Exists
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
              # cloudProvider: '{{ dig "cloudProvider" "true" . }}'
              # argocd.argoproj.io/product-{{ index .path.segments 2 }}: '{{ dig "enabled" (true) . }}'
  template:
    metadata:
      name: '{{ .name }}-apps-{{ index .path.segments 2 }}-{{ dig "enabled" "blah" . }}-{{ dig "blah" "xyz" . }}'
      annotations:
        x: |
          {{ . | mustToPrettyJson }}
    spec:
      project: "apps"
      source:
        repoURL: https://github.com/Shaked/playground
        targetRevision: main
        path: "charts/apps/{{ index .path.segments 2 }}"
        helm:
          releaseName: '{{ dig "releaseName" (printf "%s" (index .path.segments 2)) . }}'
          ignoreMissingValueFiles: true
          parameters:
          - name: region
            value: '{{ index .metadata.labels "region" }}'
          valueFiles:
          - '../../../values/common-{{ index .path.segments 2 }}.yaml'
          - '../../../values/{{ index .path.segments 2 }}/{{.name}}/values.yaml'
          - '../../../values/{{.name}}/{{ index .path.segments 2 }}/values.yaml'
      destination:
        server: "{{ .server }}"
        namespace: "{{ index .path.segments 2 }}"
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
