apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/Shaked/playground
      revision: main
      files:
        - path: values/infra/**/global/argo.yaml
      pathParamPrefix: global
  - matrix:
      generators:
      - clusters:
          pathParamPrefix: cluster
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
      - git:
          repoURL: https://github.com/Shaked/playground
          revision: main
          files:
            - path: values/infra/**/{{ index .metadata.labels "environment" }}/argo.yaml
          values:
            appEnabled: '{{ dig "enabled" "global.enabled" . }}'
          pathParamPrefix: infra
  template:
    metadata:
      name: '{{ .cluster.name }}-infra-{{ index .infra.path.segments 2}}'
      labels:
        infra-enabled: '{{ .values.appEnabled }}'
        sef2: '{{ index .infra.path.segments 2 }}'
        seg3: '{{ index .infra.path.segments 3 }}'
        environment-labels: '{{ index .metadata.labels "environment" }}'
        dig-global: '{{ global }}'
    spec:
      project: "infra"
      source:
        repoURL: https://github.com/Shaked/playground
        targetRevision: main
        path: "charts/infra/{{ index .infra.path.segments 2 }}"
        helm:
          releaseName: '{{ dig "releaseName" (printf "%s" (index .infra.path.segments 2)) . }}'
          ignoreMissingValueFiles: true
          parameters:
          - name: region
            value: '{{ index .metadata.labels "region" }}'
          - name: environment
            value: '{{ index .infra.path.segments 3 }}'
          valueFiles:
          - '../../../values/common-{{ index .infra.path.segments 2 }}.yaml'
          - '../../../values/{{ index .infra.path.segments 2 }}/{{.name}}/values.yaml'
      destination:
        server: "{{ .cluster.server }}"
        namespace: "{{ index .infra.path.segments 2 }}"
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
