apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - merge:
      mergeKeys:
      - path
      generators:
      - matrix:
          generators:
          - clusters: # 2 clusters
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
              values:
                env: '{{- `{{ index .metadata.labels "environment" }}` -}}'
                isCluterInfraEnabled: '{{- `{{ index .metadata.labels "infra-enabled" }}` -}}'
          - git: # 3 with defaults
              repoURL: https://github.com/Shaked/playground
              revision: main
              files:
                - path: charts/infra/**/argo.yaml
              pathParamPrefix: app
      - git: # 3 with defaults
          repoURL: https://github.com/Shaked/playground
          revision: main
          files:
            - path: charts/infra/{{ .app.path.basenameNormalized }}/{{ .values.env }}/argo.yaml
          pathParamPrefix: target
  template:
    metadata:
      name: '{{ .name }}-infra-{{ index .app.path.segments 2}}'
      annotations:
        x: |
          {{ . | mustToPrettyJson }}
      labels:
        infra-enabled: '{{ .enabled }}'
        app-infra-enabled: '{{ dig "app" "enabled" "false" . }}'
        defaults-infra-enabled: '{{ dig "defaults" "enabled" "false" . }}'
        sef2: '{{ index .app.path.segments 2 }}'
        environment-labels: '{{ index .metadata.labels "environment" }}'
    spec:
      project: "infra"
      source:
        repoURL: https://github.com/Shaked/playground
        targetRevision: main
        path: "charts/infra/{{ index .app.path.segments 2 }}"
        helm:
          releaseName: '{{ dig "releaseName" (printf "%s" (index .app.path.segments 2)) . }}'
          ignoreMissingValueFiles: true
          parameters:
          - name: region
            value: '{{ index .metadata.labels "region" }}'
          valueFiles:
          - '../../../values/common-{{ index .app.path.segments 2 }}.yaml'
          - '../../../values/{{ index .app.path.segments 2 }}/{{.name}}/values.yaml'
      destination:
        server: "{{ .server }}"
        namespace: "{{ index .app.path.segments 2 }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
