apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - matrix:
          generators:
          - git:
              repoURL: https://github.com/Shaked/playground
              revision: main
              files:
                - path: charts/infra/**/argo.yaml
              pathParamPrefix: app
          - git:
              repoURL: https://github.com/Shaked/playground
              revision: main
              files:
                - path: values/infra/**/argo.yaml
              pathParamPrefix: target
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
              # infra-enabled: '{{ dig "target" "enabled" (printf "%s" ("app.enabled")) . }}'
  template:
    metadata:
      name: '{{ .name }}-infra-{{ index .target.path.segments 2}}'
      labels:
        {{ . | mustToPrettyJson }}
        # app-infra-enabled: '{{ .app.enabled }}'
        target-infra-enabled: '{{ dig "target" "enabled" "blah" . }}'
        sef2: '{{ index .target.path.segments 2 }}'
        seg3: '{{ index .target.path.segments 3 }}'
        environment-labels: '{{ index .metadata.labels "environment" }}'
    spec:
      project: "infra"
      source:
        repoURL: https://github.com/Shaked/playground
        targetRevision: main
        path: "charts/infra/{{ index .target.path.segments 2 }}"
        helm:
          releaseName: '{{ dig "releaseName" (printf "%s" (index .target.path.segments 2)) . }}'
          ignoreMissingValueFiles: true
          parameters:
          - name: region
            value: '{{ index .metadata.labels "region" }}'
          - name: environment
            value: '{{ index .target.path.segments 3 }}'
          valueFiles:
          - '../../../values/common-{{ index .target.path.segments 2 }}.yaml'
          - '../../../values/{{ index .target.path.segments 2 }}/{{.name}}/values.yaml'
      destination:
        server: "{{ .server }}"
        namespace: "{{ index .target.path.segments 2 }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
