apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/Shaked/playground
          revision: main
          files:
            - path: values/infra/**/values.yaml
            - path: values/infra/**/**/values.yaml
            - path: values/infra/**/**/**/values.yaml
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
    selector:
      matchLabels:
        infra-enabled: '{{ dig "enabled" (true) . }}'
        region: '{{index .path.segments 4}}'
        cloud-provider: '{{index .path.segments 3}}'
  template:
    metadata:
      name: '{{ .name }}-infra-{{ index .path.segments 2}}'
    spec:
      project: "infra"
      source:
        repoURL: https://github.com/Shaked/playground
        targetRevision: main
        path: "charts/infra/{{ index .path.segments 2 }}"
        helm:
          releaseName: '{{ dig "releaseName" (printf "%s" (index .path.segments 2)) . }}'
          ignoreMissingValueFiles: true
          parameters:
          - name: region
            value: '{{ index .metadata.labels "region" }}'
          valueFiles:
          - '../../../values/common-{{ index .path.segments 2 }}.yaml'
          - '../../../values/{{ index .path.segments 2 }}/{{.name}}/values.yaml'
      destination:
        server: "{{ .server }}"
        namespace: "{{ index .path.segments 2 }}"
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
