apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
      - git:
          repoURL: https://github.com/Shaked/playground
          revision: main
          files:
            - path: values/infra/**/{{ dig "clusters" (index .metadata.labels "environment") "global" . }}/argo.yaml
          values:
            appEnabled: '{{ dig "enabled" true . }}'
  template:
    metadata:
      name: '{{ .name }}-infra-{{ index .path.segments 2}}'
      labels:
        infra-enabled: '{{ .values.appEnabled }}'
        sef2: '{{ index .path.segments 2 }}'
        seg3: '{{ index .path.segments 3 }}'
        environment-labels: '{{ index .metadata.labels "environment" }}'
        dig-global: '{{ dig (index .metadata.labels "environment") "global" . }}'
    spec:
      project: "infra"
      source:
        repoURL: https://github.com/Shaked/playground
        targetRevision: main
        path: "charts/infra/{{ index .path.segments 2 }}"
        helm:
          releaseName: '{{ dig "releaseName" (printf "%s" (index .path.segments 2)) . }}'
          ignoreMissingValueFiles: true
          parameters:
          - name: region
            value: '{{ index .metadata.labels "region" }}'
          - name: environment
            value: '{{ index .path.segments 3 }}'
          valueFiles:
          - '../../../values/common-{{ index .path.segments 2 }}.yaml'
          - '../../../values/{{ index .path.segments 2 }}/{{.name}}/values.yaml'
      destination:
        server: "{{ .server }}"
        namespace: "{{ index .path.segments 2 }}"
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
