apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - git:
            repoURL: https://github.com/Shaked/playground
            revision: main
            files:
              - path: values/infra/**/argo.yaml
            pathParamPrefix: app
        - clusters:
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
            values:
              env: '{{- `{{ index .metadata.labels "environment" }}` -}}'
              isCluterInfraEnabled: '{{- `{{ index .metadata.labels "infra-enabled" }}` -}}'

  template:
    metadata:
      name: '{{ .name }}-infra-{{ index .app.path.segments 2}}'
      annotations:
        x: |
          {{ . | mustToPrettyJson }}
      labels:
        infra-enabled: '{{ .enabled }}'
        app-infra-enabled: '{{ dig "app" "enabled" "false" . }}'
        defaults-infra-enabled: '{{ dig "defaults" "enabled" "false" . }}'
        sef2: '{{ index .target.path.segments 2 }}'
        environment-labels: '{{ index .metadata.labels "environment" }}'
    spec:
      project: "infra"
      source:
        repoURL: https://github.com/Shaked/playground
        targetRevision: main
        path: "charts/infra/{{ index .target.path.segments 2 }}"
        helm:
          releaseName: '{{ dig "releaseName" (printf "%s" (index .target.path.segments 2)) . }}'
          ignoreMissingValueFiles: true
          parameters:
          - name: region
            value: '{{ index .metadata.labels "region" }}'
          valueFiles:
          - '../../../values/common-{{ index .target.path.segments 2 }}.yaml'
          - '../../../values/{{ index .target.path.segments 2 }}/{{.name}}/values.yaml'
      destination:
        server: "{{ .server }}"
        namespace: "{{ index .target.path.segments 2 }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
