apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: charts-head
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
       generators:
        - git:
            repoURL: https://github.com/Shaked/playground.git
            revision: HEAD
            directories:
            - path: charts/*
        - list:
            elements:
            - cluster: engineering-dev
              url: https://kubernetes.default.svc
            - cluster: engineering-prod
              url: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{.cluster}}-{{.path.basenameNormalized}}"
    spec:
      project: "default"
      source:
        repoURL: "https://github.com/Shaked/playground.git"
        targetRevision: HEAD
        path: "{{.path}}"
      destination:
        server: "{{.url}}"
        namespace: "{{.cluster}}"
